In [3]:
import numpy as np

array1 = np.array([1,2,3,4])
array2 = np.array([5,6,7,8])

matrix = np.array([
    [1,2,3,4],
    [5,6,7,8]
])

matrix.ndim
matrix.size
matrix.shape
# array.shape
# array.reshape(2,4)
# # Stacking arrays
# np.vstack((array1, array2))
# np.hstack((array1, array2))
# # Splitting arrays
# np.hsplit(matrix, 2)
# np.vsplit(matrix, 2)


(2, 4)

In [27]:
import numpy as np

# Solving systems of linear equation AX = B
# Where A is the coeficient matrix and B is the equal values matrix

A = np.array([
    [1,1,1],
    [2,-1,1],
    [1,2,-1]
])

B = np.array([6,2,7])

np.linalg.solve(A,B)
Det = np.linalg.det(A)
print(f"The determinant of A is {Det:.2f}")

np.hstack((A,B.reshape(3,1)))

The determinant of A is 7.00


array([[ 1,  1,  1,  6],
       [ 2, -1,  1,  2],
       [ 1,  2, -1,  7]])

In [5]:
import numpy as np

A = np.array([
    [4,-3,1],
    [2,1,3],
    [-1,2,-5]
])

b = np.array([-10,0,17])
np.shape(A)
np.linalg.solve(A,b)
det = np.linalg.det(A)

print(f"The determinant of\n {A} is \n{det:.2f}")

The determinant of
 [[ 4 -3  1]
 [ 2  1  3]
 [-1  2 -5]] is 
-60.00


In [14]:
import numpy as np

scalar = np.array(12);
print(scalar.ndim)
scalar = np.array([12,12,4]);
print(scalar.ndim)
print(scalar.shape)
scalar = np.array([[12]]);
print(scalar.ndim)
print(scalar.shape)

# Normally numpy consider a vector as a single object not explicit telling that it is a column vector or a row vector like (1,3) or (3,1), it will just give you (3,), but if you want to explicit create a column of a row vector you can use mutiple dimension approach

column_vector = np.array([[2],
                          [4],
                          [6],
                          [8]])
print(column_vector.shape)

row_vector = np.array([[1,2,3,4]])
row_vector.shape

0
1
(3,)
2
(1, 1)
(4, 1)


(1, 4)