In [ ]:
import numpy as np

# ML functions

x = np.array([1,2,3,4,5])

linear = 2*x + 4
quadratic = x**2 + 6
exponential = np.exp(x)
logarithmic = np.log(x)
sigmoid = 1 / (1 + np.exp(-x))
ReLU = np.maximum(0,x)

print("linear: \n", linear)
print("quadratic: \n", quadratic)
print("exponential: \n", exponential)
print("logarithmic: \n", logarithmic)
print("Sigmoid: \n", sigmoid)
print("ReLU: \n", ReLU)


linear: 
 [ 6  8 10 12 14]
quadratic: 
 [ 7 10 15 22 31]
exponential: 
 [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
logarithmic: 
 [0.         0.69314718 1.09861229 1.38629436 1.60943791]
Sigmoid: 
 [0.73105858 0.88079708 0.95257413 0.98201379 0.99330715]
ReLU: 
 [1 2 3 4 5]
